=== ComNetsHH/omnetpp-tsch/etc/TSCH_Schedule.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TSCHSchedule" type="TSCHScheduleType"/>
  <xs:complexType name="OptionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:boolean" name="tx" use="optional"/>
        <xs:attribute type="xs:boolean" name="rx" use="optional"/>
        <xs:attribute type="xs:boolean" name="shared" use="optional"/>
        <xs:attribute type="xs:boolean" name="timekeeping" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="TypeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:boolean" name="normal" use="optional"/>
        <xs:attribute type="xs:boolean" name="advertising" use="optional"/>
        <xs:attribute type="xs:boolean" name="advertisingOnly" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="VirtualType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:integer" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="NeighborType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="optional"/>
        <xs:attribute type="xs:string" name="address" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LinkType">
    <xs:sequence>
      <xs:element type="OptionType" name="Option" minOccurs="0" maxOccurs="1"/>
      <xs:element type="TypeType" name="Type" minOccurs="0" maxOccurs="1"/>
      <xs:element type="VirtualType" name="Virtual" minOccurs="0" maxOccurs="1"/>
      <xs:element type="NeighborType" name="Neighbor" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:integer" name="slotOffset" use="required"/>
    <xs:attribute type="xs:integer" name="channelOffset" use="required"/>
  </xs:complexType>
  <xs:complexType name="SlotframeType">
    <xs:sequence>
      <xs:element type="LinkType" name="Link" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute type="xs:integer" name="handle" use="required"/>
    <xs:attribute type="xs:integer" name="macSlotframeSize" default="101"/>
  </xs:complexType>
  <xs:complexType name="TSCHScheduleType">
    <xs:sequence>
      <xs:element type="SlotframeType" name="Slotframe" maxOccurs="unbounded" minOccurs="1">
        <xs:annotation>
          <xs:documentation>Slotframe</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ComNetsHH/omnetpp-tsch/src/linklayer/ieee802154e/Tsch_Schedule_example.xml
<?xml version="1.0"?>
<TSCHSchedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TSCH_SCHEDULE.xsd">
  <!-- Slotframe -->
  <Slotframe handle="0" macSlotframeSize="101">
    <Link slotOffset="0" channelOffset="0">
		<Option tx="true" rx="true" shared="true" timekeeping="false" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Virtual id="0" />
		<Neighbor path="host[0]" />
	</Link>
	    <Link slotOffset="50" channelOffset="5">
		<Option tx="true" rx="true" shared="true" timekeeping="false" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Virtual id="0" />
        <Neighbor address="FF:FF:FF:FF:FF:FF" />
	</Link>
  </Slotframe>
  <Slotframe handle="0" macSlotframeSize="101">
    <Link slotOffset="0" channelOffset="0">
		<Option tx="true" rx="true" shared="true" timekeeping="false" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Virtual id="0" />
		<Neighbor path="host[0]" />
	</Link>
  </Slotframe>
</TSCHSchedule>

=== ComNetsHH/omnetpp-tsch/simulations/wireless/nic/WAIC_Wlan_On_Schedule_host_5.xml
<?xml version="1.0"?>
<TSCHSchedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TSCH_SCHEDULE.xsd">
  <!-- Slotframe -->
  <Slotframe macSlotframeSize="101">
    <Link slotOffset="3" channelOffset="1">
		<Option tx="true" rx="false" shared="false"/>
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:03" />
	</Link>
	<Link slotOffset="10" channelOffset="4">
		<Option tx="true" rx="false" shared="true"/>
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:03" />
	</Link>
	<Link slotOffset="15" channelOffset="2">
		<Option tx="true" rx="false" shared="true"/>
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:03" />
	</Link>
  </Slotframe>
</TSCHSchedule>

=== ComNetsHH/omnetpp-tsch/simulations/wireless/aircraft/WAIC_Wlan_On_Schedule_host_0.xml
<?xml version="1.0"?>
<TSCHSchedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TSCH_SCHEDULE.xsd">
  <!-- Slotframe -->
  <Slotframe macSlotframeSize="101">
    <Link slotOffset="1" channelOffset="2">
		<Option tx="false" rx="true" shared="true"/>
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
	<Link slotOffset="4" channelOffset="2">
		<Option tx="false" rx="true" shared="true"/>
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
	<Link slotOffset="9" channelOffset="2">
		<Option tx="false" rx="true" shared="true"/>
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
  </Slotframe>
</TSCHSchedule>

=== ComNetsHH/omnetpp-tsch/simulations/wireless/waic/itnac_static_schedule.xml
<?xml version="1.0"?>
<TSCHSchedule xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TSCH_SCHEDULE.xsd">
  <!-- Slotframe -->
  <Slotframe macSlotframeSize="101">
    <Link slotOffset="0" channelOffset="0">
		<Option tx="true" rx="false" shared="false"/>
		<Virtual id="0" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
	    <Link slotOffset="1" channelOffset="0">
		<Option tx="false" rx="true" shared="false"/>
		<Virtual id="0" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
	<Link slotOffset="2" channelOffset="0">
		<Option tx="false" rx="true" shared="false"/>
		<Virtual id="1" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
	<Link slotOffset="3" channelOffset="0">
		<Option tx="true" rx="false" shared="false"/>
		<Virtual id="1" />
		<Type normal="true" advertising="false" advertisingOnly="false" />
		<Neighbor address="0A:AA:00:00:00:02" />
	</Link>
  </Slotframe>
</TSCHSchedule>
